### ISSUE TITLE
Comparison with other stylus packages

### ISSUE THREAD

**Issue by dandv** [juliancwirko/meteor-s-jeet#4]
There are [many stylus packages on Atmosphere](https://atmospherejs.com/?q=stylus). How does this one compare, esp. with @furrio's https://github.com/furrio/meteor-stylus-multi/ ?

PS: some of those stylus packages on Atmosphere are abandoned and should be flagged. Help with flagging would be appreciated.

**Comment by juliancwirko** [comment]
At the beggining it was a part of my Meteor boilerplate..
I know that it will be always up to date with Jeet, but of course it will be cool if there will be one very well maintained package with Jeet and Autoprefixer.
